### ISSUE TITLE
Using Backtic (`) Around Table Name Errors Out 

### ISSUE THREAD

**Issue by jonnyg321** [amayer5125/php-database-class#1]
When attempting to use the sort_by parameter, the function outputs an error and does not return the proper array when using backtics around the table name.

Example:

QUERY: $x = $db->query('SELECT * FROM `table_name`', null, null, false, true);

RESULT: query(): field is empty. Cannot assign key to sorted array.

**Comment by amayer5125** [comment]
Fixed by 82dc502a793a6b3826556c24fd5d12fe45940eff
